- name: Install plugins
  grafana_plugin:
    name: "{{ item }}"
    grafana_plugins_dir: "{{ grafana_data_dir }}/plugins"
    state: present
  with_items: "{{ grafana_plugins | difference(installed_plugins.files) }}"
  notify:
    - restart grafana
